from typing import Any

import cloudpickle
from typing_extensions import override

from flink_agents.api.event import Event, InputEvent, OutputEvent
from flink_agents.api.workflow_runner_context import WorkflowRunnerContext


def get_runner_context(id: Any, jctx: Any):
    return RunnerContext(id, jctx)

def get_python_object(bytesObject: bytes):
    return cloudpickle.loads(bytesObject)

def get_input_event(input: str):
    return InputEvent(input=int(input))

class RunnerContext(WorkflowRunnerContext):
    def __init__(self, id: Any, jctx: Any):
        self.__id = id
        self.jctx = jctx

    @property
    def session_id(self):
        return self.__id

    @override
    def send_event(self, event: Event):
        try:
            if isinstance(event, OutputEvent):
                self.jctx.sendEvent(
                    f"{type(event).__module__}.{type(event).__name__}",
                    self.__id,
                    cloudpickle.dumps(event.output),
                )
            else:
                self.jctx.sendEvent(f"{type(event).__module__}.{type(event).__name__}", self.__id, cloudpickle.dumps(event))
        except Exception as e:
            print(f"Error adding event: {e}")

    @override
    def get_j_ctx(self):
        return self.jctx

    @override
    def add_output(self, output: Any) -> None:
        """Add an output generate by workflow execution to the context.

        Parameters
        ----------
        output : Any
            The output to be added to the queue.
        """
        pass

    @override
    def get_outputs(self):
        """Add an output generate by workflow execution to the context.

        Returns:
        -------
        deque[Any]
            The outputs generated by workflow execution on this context.
        """
        pass

    @override
    def clear_output(self) -> None:
        """Clear outputs stored in this context."""
        pass